### ISSUE TITLE
ENOTFOUND Error when sending sms

### ISSUE THREAD

**Issue by 3210jr** [AfricasTalkingLtd/africastalking-node.js#41]
Hey,

Getting the following error whenever I try sending a message either through the sandbox api and even the production one:
```
{ Error: getaddrinfo ENOTFOUND api.africastalking.com api.africastalking.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.africastalking.com',
  host: 'api.africastalking.com',
  port: 443 }
```

Thanks!

**Comment by aksalj** [comment]
Seems like a network issue... :thinking:
